name: The One Power
main: com.pulsior.theonepower.TheOnePower
version: 1.0
author: Pulsior
commands:
     embrace:
       description: Embrace saidar and let the One Power flow through you!
       usage: /<command>
       permission: theonepower.channel
       permission-message: You don't have permission to do this
     release:
       description: Release saidar and return to your ordinary self
       usage: /<command>
       permission: theonepower.channel
       permission-message: You don't have permission to do this
     angreal:
       description: Get an angreal, ter'angreal or sa'angreal
       usage: /<command>
       permission: <plugin name>.basic
       permission-message: You don't have permission to do this
     dream:
       description: Travel to Tel'aran'rhiod
       usage: /<command>
       permission: <plugin name>.basic
       permission-message: You don't have permission to do this
     remember:
       description: Remember a place, so you can revisit it in Tel'aran'rhiod easily
       usage: /<command> [name of the memory]
       permission: theonepower.remember
       permission-message: You don't have permission to do this
     forget:
       description: Forget a place you remembered
       usage: /<command> [name of the memory]
       permission: theonepower.remember
       permission-message: You don't have permission to do this
     stats:
       description: Retrieve stats about your level progress and your memories
       usage: /<command>
       permission: theonepower.stats
       permission-message: You don't have permission to do this 
permissions:
     theonepower.channel:
       description: Allow players to embrace, use and release saidar
       default: true
     theonepower.remember:
       description: Allow players to remember and forget locations
       default: true
     theonepower.stats:
       description: Allow players to access their stats, to see their level progress
       default: true
     theonepower.angreal:
       description: Allow players to cheat an angreal
       default: op
     theonepower.dream:
       description: Allow players to cheat themselves to the Unseen Land
       default: op
     